In [3]:
pip install numpy


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [2]:
x = [[1,2,3], [4,5,6], [7,8,9]]
np.array(x, float)
np.array(x).cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [3]:
def byfive(num):
    return num*5

In [5]:
byfive(np.array(x))

y = np.array(x)

In [28]:
y.dtype

dtype('int64')

In [29]:
byfive(y)

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
lin = np.linspace(1,10,21)
print(lin)
lin2 = np.linspace(1,10) ## why is it inclusive of 10?
print(lin2)
lin3 = np.linspace(1,10,5)
print(lin3)
lin4 = np.linspace(0,49)
print(lin4)
lin5 = np.linspace(0,20,21)
print(lin5)

[ 1.    1.45  1.9   2.35  2.8   3.25  3.7   4.15  4.6   5.05  5.5   5.95
  6.4   6.85  7.3   7.75  8.2   8.65  9.1   9.55 10.  ]
[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.    3.25  5.5   7.75 10.  ]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]
[ 0.  1.  2.  3.  4.  5.  

In [54]:
ar = np.arange(0,22,7)
print(ar)
z = np.zeros(500,int)
print(z)
w = np.ones(500,int)
print(w)

[ 0  7 14 21]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 

In [7]:
np.random.rand(10,6)

array([[0.91592673, 0.25808533, 0.06475215, 0.12206002, 0.58383266,
        0.01684787],
       [0.85200582, 0.98814841, 0.53286662, 0.52220352, 0.62755743,
        0.65592146],
       [0.38212552, 0.85094169, 0.910149  , 0.50823087, 0.84079816,
        0.43051404],
       [0.80280609, 0.33709395, 0.56225047, 0.70111754, 0.23795673,
        0.82802531],
       [0.44286959, 0.18593527, 0.05040491, 0.26195718, 0.0300596 ,
        0.5155065 ],
       [0.89017945, 0.47429107, 0.02101057, 0.74077157, 0.88786274,
        0.90108552],
       [0.08097597, 0.09435364, 0.58352144, 0.54284263, 0.39602235,
        0.56567283],
       [0.23779645, 0.5919041 , 0.17680806, 0.81021713, 0.32380062,
        0.5663097 ],
       [0.58033546, 0.30276395, 0.70715103, 0.38787589, 0.8394544 ,
        0.0358689 ],
       [0.34393407, 0.12912736, 0.08275043, 0.27594793, 0.56005197,
        0.64871563]])

In [6]:
np.random.rand(10,6)
np.random.randint(5,500, (5,5))

array([[465, 386,  44, 271, 334],
       [  6, 191, 386, 104, 218],
       [190, 279, 138, 326, 261],
       [341,  12, 400, 340,  27],
       [479,  53, 497, 382, 402]])

In [61]:
byfive(y.reshape(1,9))

array([[ 5, 10, 15, 20, 25, 30, 35, 40, 45]])

In [60]:
y.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
x = [1,2,3,4,5,3,2,1]
x.sort( )

In [68]:
sorted(x)

[1, 1, 2, 2, 3, 3, 4, 5]

In [ ]:
# ********
# .ravel() and .flatten() both convert to a one dimensional array
# .ravel() returns a view, .flatten() returns a copy which means .ravel() will save the array whereas .flatten shows a new array 
y = y.ravel() # like sorted 
print(y)
y = y.flatten()
print(y)
# DOESNT WORK I NEED HELP ON THIS ONE
# It's definitely doing something different but I can't tell what
#********

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [70]:
x = np.random.randint(5,500, (10,10))
print(x)

[[453  20 339 147 373 336  23 212  24 126]
 [290 353 333 218  78  71 342 189 162 356]
 [348 225 475 278  26 346 456 155 475 279]
 [416 121 460 112 162 444 224 208 125  65]
 [190 315 343 187 342  68  34 225 421 192]
 [ 64 353 244 293 460 118 456 309 246  17]
 [ 91 193 474  85  17 232 340 118  16  58]
 [318 477 408 482  27  45 175  90 390 459]
 [159 124 267  38 281  69 336 133  72 138]
 [481 453  34  14  67  54  51 222 485 370]]


In [71]:
x.ravel()

array([453,  20, 339, 147, 373, 336,  23, 212,  24, 126, 290, 353, 333,
       218,  78,  71, 342, 189, 162, 356, 348, 225, 475, 278,  26, 346,
       456, 155, 475, 279, 416, 121, 460, 112, 162, 444, 224, 208, 125,
        65, 190, 315, 343, 187, 342,  68,  34, 225, 421, 192,  64, 353,
       244, 293, 460, 118, 456, 309, 246,  17,  91, 193, 474,  85,  17,
       232, 340, 118,  16,  58, 318, 477, 408, 482,  27,  45, 175,  90,
       390, 459, 159, 124, 267,  38, 281,  69, 336, 133,  72, 138, 481,
       453,  34,  14,  67,  54,  51, 222, 485, 370])

In [61]:
import numpy as np
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [62]:
a1 = a.ravel()

In [63]:
a1[0] = 200
a

array([[200,   2],
       [  3,   4]])

In [64]:
a2 = a.flatten()
a2[1] = 4000

In [65]:
a

array([[200,   2],
       [  3,   4]])

In [14]:
f = np.array([["1","2","3"],["4","5","6"],["7","8","9"]])
f.astype(float)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [15]:
f.astype(int)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
f.astype(str)

array([['1', '2', '3'],
       ['4', '5', '6'],
       ['7', '8', '9']], dtype='<U1')

In [71]:
f.astype(int)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
a = np.array(([1,2,3],[3,4,5],[7,9,11]))

b = np.array(([6,7,8],[9,10,11]))

c = np.array(([2,4,6],[8,10,12], [14,16,18]))

d = np.array(([1,3,5,6],[7,9,11,7], [13,15,17,8]))

print(np.concatenate((a,b), axis=0))



[[ 1  2  3]
 [ 3  4  5]
 [ 7  9 11]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
print(byfive(np.concatenate((a,d), axis=1)))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4

In [18]:
print(y)
print(f.astype(int))
f.astype(int) * y

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [24]:
z = [[2,2,2],[3,3,3]]

In [27]:
y * z

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [26]:
byfive(np.concatenate((y,z), axis=0))

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [10, 10, 10],
       [15, 15, 15]])

In [ ]:
print(y.sum())
print(y.mean())
print(y.max())
print(y.min())
print(y.cumsum())
print(y.std())
dir(y)
np.array(y)


45
5.0
9
1
[ 1  3  6 10 15 21 28 36 45]
2.581988897471611


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
a = [[6,13,26],[2, 6,10],[0, 5,8]] ### [songlowval,songmidval,songhighval] likes,comments,followers

a = np.array(a)

In [45]:
b =[3,5,2]
b = np.array(b)
np.dot(a,b)

array([135,  56,  41])

In [ ]:
## I understand numpy is a library of classes with functions that relate to each specific class
## I understand roughly 20 functions -- I still need to use them more to understand them better
## I understand that nummpy works with vectors and arrays and that vectors are one dimensional arrays
## I also understand broadcasting which is a big function of numpy

In [ ]:
np.where(b>=3,1,0), ## where b is greater than or equal to 3, return 1, else return 0
np.where(b>=3) ## where b is greater than or equal to 3, return the indices

array([1, 1, 0])

In [51]:
print(np.unique(z))
print(np.unique(z, return_counts=True))

[2 3]
(array([2, 3]), array([3, 3]))
